name: 新题追加
about: 我有新的题要投稿！( •̀ ω •́ )✧
title: 新的选择题/填空题
labels: enhancement
assignees: ""


body:
- type: checkboxes
  attributes:
    label: 提交前必读
    options: 
      - label: 一次只能提交一道题哦！
        required: true
- type: textarea
  label: 详细信息
  attributes:
    value: |
      **题目题干**
      2. 你说得对，但是原神是一款…
      |
      **答案**
      由米哈游研发的3D开放世界冒险类游戏
      |
      **考点**
      原神圣经
      |
      **解析**
      广告词大概就是这样写的罢🧔🏻‍♂️
  validations:
    required: true
